### ISSUE TITLE
Revision tag

### ISSUE THREAD

**Issue by bondie** [Sylius/BootstrapTheme#14]
Hello, is there any chance to create new tag for master branch? We have Sylius plugin which has dependency on Sylius/BootstrapTheme and it would be nice to have dependency on specific version instead of dev-master. Thanks!

**Comment by kulczy** [comment]
hi @bondie next month we're releasing Sylius 1.6 and I think this will be a good time to start tagging the theme

**Comment by oallain** [comment]
> hi @bondie next month we're releasing Sylius 1.6 and I think this will be a good time to start tagging the theme

Very good news :tada:

**Comment by misaon** [comment]
@kulczy 1.6 is already released, some news?

**Comment by misaon** [comment]
Funny 😄 ....

**Comment by kulczy** [comment]
done 😄
