### ISSUE TITLE
Update to sylius 1.7 ?

### ISSUE THREAD

**Issue by imajim** [Sylius/BootstrapTheme#34]
Hello,

This theme is still alive ? because no update or no new release since sylius 1.7

++++

**Comment by pocky** [comment]
@kulczy Do you need help? I have time because of COVID...

**Comment by pocky** [comment]
ping @pjedrzejewski with :heart:

**Comment by oallain** [comment]
IMO, yes this theme need to be updated to Sylius 1.7.

Someone needs to take the time to do it :wink:

**Comment by tavy315** [comment]
@oallain good advice, why don't you take the time to do it? 🤔

**Comment by pocky** [comment]
@tavy315 And you? Your comment is....

BTW...

Quick update: All PR (except #22 because I don't have this issue) are merged on my fork: https://github.com/pocky/BootstrapTheme
I hope I will have time to update the theme (sylius events instead of sonata) between now and end of the next week.

**Comment by pocky** [comment]
New update: Thanks to @pamil, I am collaborator on this project.

**Comment by tavy315** [comment]
Email templates also have been changed, see [orderConfirmation.html.twig](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/views/Email/orderConfirmation.html.twig) for example.

**Comment by 4c0n** [comment]
@pocky Where can we find your WIP, do you have a branch in a fork or perhaps here?
Going to need this pretty soon as well, so might be able to jump in and help out as well.
Can't deal with the CSS version of Semantic UI for much longer...

**Comment by pocky** [comment]
@4c0n Master will be compatible (but not 100% up to date) just after #37 and tag 0.1.1.

**Comment by pocky** [comment]
Master is now compatible with Sylius ^1.7 but there is a lot a work on templates before a true 0.2.0.

**Comment by pocky** [comment]
Hello,

I need help for the "click click click" task ;) : https://github.com/Sylius/BootstrapTheme/pull/39
