### ISSUE TITLE
the dependency of bootstrap.native should be set to version 2.0.27 or include directly the file bootstrap-native.js without version

### ISSUE THREAD

**Issue by htaoufikallah** [Sylius/BootstrapTheme#40]
Hello there,
I followed the docs on sylius website and when I tried run yarn electron dev I get an error that the bootstrap-native-v4.js file doesn't exists, then I checked bootstrap.native and I found out that they have dropped version 3 support on the 3.0.0 release so the working version without changing anything is 2.0.27 or include the bootstrap-native.js file directly without the version suffix

**Comment by 4c0n** [comment]
Same problem here.
