### ISSUE TITLE
Can't pass the shipping address step

### ISSUE THREAD

**Issue by htaoufikallah** [Sylius/BootstrapTheme#42]
I can't pass the shipping address step on the checkout even thought that I fill in the required fields but the form always say that theses fields are required:

- First name
- Last name
- Street address
- City
- Postcode

Am I missing something?

**Comment by htaoufikallah** [comment]
Finnaly by reading the section **Billing and shipping addresses have been switched with one another** in [the upgrade guide to sylius 1.7 version](https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.7.md#billing-and-shipping-addresses-have-been-switched-with-one-another) and by comparing the master branch code and the 0.1.1 release I found out that I don't have the same code.
So the solution was to change the minimum stability to dev and set the sylius/bootstrap-theme version to dev master
I think a new release with latest code should be released or am I still missing something?

**Comment by chrissnyder2337** [comment]
@htaoufikallah I am experiencing the same thing too. Thank you for letting me know that using the unreleased branch may work. I will try that next.

**Comment by htaoufikallah** [comment]
@chrissnyder2337 you are welcome, good luck

**Comment by Sander-Voogt** [comment]
The shippingaddress and the billingaddress form are turned in position

This change to the code solved the problem #45

**Comment by htaoufikallah** [comment]
@Sander-Voogt but I think that the code in master branch is correct and it is working for me and your change in the mentionned [pull request](https://github.com/Sylius/BootstrapTheme/pull/45/files) is reverting back that file to version [v0.1.1](https://github.com/Sylius/BootstrapTheme/releases/tag/v0.1.1) 
In the upgrade guide it is written that the shipping address was the default one [read here](https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.7.md#billing-and-shipping-addresses-have-been-switched-with-one-another)
I searched the commit list and it was fixed in [this commit](https://github.com/Sylius/BootstrapTheme/commit/a6341bbb7f7bb503edb8183cd1642dd08466616b#diff-f59e587c3f155bfed5aaa366ff837a65)  which fix [this issue](https://github.com/Sylius/BootstrapTheme/issues/28) reported before.
So the issue is fixed and merged but I think is not yet released

I'm closing this issue for now, feel free to open it if you think it should be
