### ISSUE TITLE
Use the documentation install doc

### ISSUE THREAD

**Issue by jbcr** [Sylius/BootstrapTheme#55]
Update readme to use the same installation process than documentation: https://docs.sylius.com/en/latest/book/themes/bootstrap-theme.html

This procedure is better to keep the template up to date.

**Comment by pocky** [comment]
Hello, we already have a link in README:

The instructions below refer to an installation in the theme folder. Installation as a composer dependency (with child theme) [is also documented](https://docs.sylius.com/en/latest/book/themes/bootstrap-theme.html).

**Comment by jbcr** [comment]
What is the recommended installation method?

The recommended method needs high visibility.

**Comment by pocky** [comment]
Don't know what to say except "it depends".

My personal preference: composer dependency with child-theme. But I work with agencies who don't want to use child-theme because an update could break their work.

**Comment by jbcr** [comment]
I understand. This issue is not solvable. I close it.
