### ISSUE TITLE
Deleting addresses from address book

### ISSUE THREAD

**Issue by jeroendk** [Sylius/BootstrapTheme#8]
The delete button in the address book is not working. This is because you need to submit a form here with the `DELETE` HTTP method instead of outputting a `GET` link:
   
    <a href="{{ path('sylius_shop_account_address_book_delete', {'id': address.id}) }}" class="btn btn-link text-muted">{{ 'sylius.ui.delete'|trans }}</a>

If you output it like a form, it will work:

```
<!--BootstrapTheme/SyliusShopBundle/views/Account/AddressBook/_item.html.twig -->

<form action="{{ path('sylius_shop_account_address_book_delete', {'id': address.id}) }}" method="post">
    <input name="_method" type="hidden" value="DELETE">
    <button class="btn btn-link text-muted">
       {{ 'sylius.ui.delete'|trans }}
    </button>
    <input type="hidden" name="_csrf_token" value="{{ csrf_token(address.id) }}"/>
</form>       
```

The default Sylius UI theme also adds a confirmation modal to delete actions, is this also available in the Bootstrap theme?

**Comment by kulczy** [comment]
@jeroendk thanks! I fixed it 7403eced70460a44ec7995ae28e051f3683f04c6 and for now, I added a simple native confirm
